using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using System.Collections.Generic;
using System.IO;

// Written by: Alex Farber
//
// alexm@cmt.co.il
// Modify by: Marcelo Lemes
//lemmarcelo@gmail.com


namespace DropFiles1
{
	/// <summary>
    /// Windows form application which opens files
    /// using File - Open menu item or dragged from
    /// Windows Explorer.
    /// Class DragDropManager is used to implement
    /// drag-and-drop feature.
    /// 
    /// </summary>
	public class Form1 : System.Windows.Forms.Form, IDropFileTarget
	{
        #region Members

        private DragDropManager m_DragDropManager;

        #endregion

        #region Members Generated by Designer

        private System.Windows.Forms.MainMenu mainMenu1;
        private System.Windows.Forms.MenuItem menuItem1;
        private System.Windows.Forms.MenuItem menuItem3;
        private System.Windows.Forms.MenuItem mnuFileExit;
        private System.Windows.Forms.MenuItem menuItem2;
        private System.Windows.Forms.MenuItem mnuHelpAbout;
        private System.Windows.Forms.ListBox lstFiles;

        #endregion

        private FolderBrowserDialog camCurso;
        private IContainer components;
        private Label label1;
        String[] DiretorioCur = new string[] { };

        #region Constructor, Destructor

		public Form1()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

        #endregion

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.mainMenu1 = new System.Windows.Forms.MainMenu(this.components);
            this.menuItem1 = new System.Windows.Forms.MenuItem();
            this.menuItem3 = new System.Windows.Forms.MenuItem();
            this.mnuFileExit = new System.Windows.Forms.MenuItem();
            this.menuItem2 = new System.Windows.Forms.MenuItem();
            this.mnuHelpAbout = new System.Windows.Forms.MenuItem();
            this.lstFiles = new System.Windows.Forms.ListBox();
            this.camCurso = new System.Windows.Forms.FolderBrowserDialog();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // mainMenu1
            // 
            this.mainMenu1.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
            this.menuItem1,
            this.menuItem2});
            // 
            // menuItem1
            // 
            this.menuItem1.Index = 0;
            this.menuItem1.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
            this.menuItem3,
            this.mnuFileExit});
            this.menuItem1.Text = "Arquivo";
            this.menuItem1.Click += new System.EventHandler(this.menuItem1_Click);
            // 
            // menuItem3
            // 
            this.menuItem3.Index = 0;
            this.menuItem3.Text = "-";
            // 
            // mnuFileExit
            // 
            this.mnuFileExit.Index = 1;
            this.mnuFileExit.Text = "Sair";
            this.mnuFileExit.Click += new System.EventHandler(this.mnuFileExit_Click);
            // 
            // menuItem2
            // 
            this.menuItem2.Index = 1;
            this.menuItem2.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
            this.mnuHelpAbout});
            this.menuItem2.Text = "Ajuda";
            // 
            // mnuHelpAbout
            // 
            this.mnuHelpAbout.Index = 0;
            this.mnuHelpAbout.Text = "Sobre";
            this.mnuHelpAbout.Click += new System.EventHandler(this.mnuHelpAbout_Click);
            // 
            // lstFiles
            // 
            this.lstFiles.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstFiles.ItemHeight = 16;
            this.lstFiles.Location = new System.Drawing.Point(7, 17);
            this.lstFiles.Name = "lstFiles";
            this.lstFiles.Size = new System.Drawing.Size(468, 116);
            this.lstFiles.TabIndex = 0;
            this.lstFiles.SelectedIndexChanged += new System.EventHandler(this.lstFiles_SelectedIndexChanged);
            // 
            // camCurso
            // 
            this.camCurso.RootFolder = System.Environment.SpecialFolder.MyComputer;
            this.camCurso.ShowNewFolderButton = false;
            this.camCurso.HelpRequest += new System.EventHandler(this.camCurso_HelpRequest);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(323, 155);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(155, 16);
            this.label1.TabIndex = 1;
            this.label1.Text = "lemmarcelo@gmail.com";
            this.label1.Click += new System.EventHandler(this.label1_Click);
            // 
            // Form1
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 15);
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.ClientSize = new System.Drawing.Size(481, 174);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lstFiles);
            this.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.ImeMode = System.Windows.Forms.ImeMode.Off;
            this.KeyPreview = true;
            this.MaximizeBox = false;
            this.Menu = this.mainMenu1;
            this.Name = "Form1";
            this.Text = "Pasta Mover";
            this.TopMost = true;
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
		#endregion

        #region Main Function

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		static void Main() 
		{
			Application.Run(new Form1());
		}

        #endregion

        #region Other Functions


        /// <summary>
        /// Open file or files passed as array.
        /// 
        /// Called from mnuFileOpen_Click or from (when user selects
        /// File - Open menu item) or from DragDropManager
        /// (when user drops files from Windows Explorer)
        /// </summary>
        /// <param name="a">Array of file names</param>
        public void OpenFiles(Array a)
        {
            // If our application can open only one file, we can process
            // here only first element of array or give some error message
            // in the case array contains more than one file.
            //
            // In this sample I allow to open number of files showing 
            // their names in list box.
            
            string sError = "";
            string sFolder;
            string valorAlbumAtual="";
            string valorPasta="";
            
            List<string> arquivosPesquisa = new List<string>();
            List<string> valorPath = new List<string>();
            List<string> valorSubPath = new List<string>();
            string targetPath="";
            lstFiles.Items.Clear();




            valorAlbumAtual = a.GetValue(0).ToString();           // file name
            valorPath.AddRange(valorAlbumAtual.Split('\\'));

            valorPasta = valorPath[valorPath.Count - 1];
            valorPath.Remove(valorPasta);
            valorAlbumAtual = valorPath[valorPath.Count - 1];
            valorPath.Remove(valorAlbumAtual);

          //  lstFiles.Items.Add(valorFoto + " movido");
            foreach (String s in valorPath)
            {
                targetPath = targetPath + s + "\\";
            }

                        
         
          //  MessageBox.Show(""+contPastasMontagem);

            targetPath = "";
            valorPath.Clear();

            // process all files in array
            for ( int i = 0; i < a.Length; i++ )
            {
                
              

                    sFolder = a.GetValue(i).ToString();           // file name

             
                    // Check file name
                    // (Let's say we don't accept non-existing files or directories)
                  //  FileInfo info = new FileInfo(sFile);


                    {

                     


                        valorAlbumAtual = a.GetValue(i).ToString();           // file name
                        valorPath.AddRange(valorAlbumAtual.Split('\\'));

                        valorPasta = valorPath[valorPath.Count - 1];
                        valorPath.Remove(valorPasta);
                        valorAlbumAtual = valorPath[valorPath.Count - 1];
                        valorPath.Remove(valorAlbumAtual);
                        //valorFotoNome = valorFoto.Substring(0,valorFoto.Length-4);
                        

                        lstFiles.Items.Add(valorPasta + " movido");
                        foreach (String s in valorPath)
                        {
                            targetPath = targetPath + s + "\\";
                        }
                      
                   
                        targetPath = targetPath +valorPasta + "\\"+ valorAlbumAtual;
                        
                        lstFiles.Items.Add("Movido em " + targetPath+valorPasta);

                        try
                        {
                            if (!Directory.Exists(targetPath))
                            {
                                try
                                {
                                    Directory.CreateDirectory(targetPath);
                                }
                                catch
                                {
                                }
                            }

                            if (Directory.Exists(targetPath))
                            {
                                // This statement ensures that the file is created,
                                // but the handle is not kept.
                                try
                                {
                                    

                                    arquivosPesquisa.AddRange(Directory.GetFiles(sFolder));

                                    foreach(String s in arquivosPesquisa){
                                        valorSubPath.AddRange(s.Split('\\'));
                                        string aux = valorSubPath[valorSubPath.Count - 1];

                                        try
                                        {
                                            File.Move(s,targetPath+"\\"+aux);
                                        }
                                        catch { 

                                        }
                                     
                                    }
                                    try
                                    {
                                        Directory.Delete(sFolder);
                                    }
                                    catch
                                    { 
                                    }
                                }
                                catch
                                {
                                    // MessageBox.Show("Falha ao criar pasta removidas");
                                }
                            }



                            
                        }
                        catch
                        {

                            MessageBox.Show("Falha ao Pasta arquivo");
                        }
                        finally
                        {




                            valorPath.Clear();
                            valorAlbumAtual = "";
                            valorPasta = "";
                            targetPath = "";

                        }
                    }
           

           
            // fim do laço FOR
            }

            // Drop directory from Explorer to this form to see error message:
            if ( sError.Length > 0 )
                MessageBox.Show(this, sError, "Erro ao abrir arquivo");
        }


        #endregion

        #region Message Handlers

        /// <summary>
        /// Initialize Drag-Drop manager
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Form1_Load(object sender, System.EventArgs e)
        {
            m_DragDropManager = new DragDropManager();
            m_DragDropManager.Parent = this;
        }


        /// <summary>
        /// File - Exit menu item
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void mnuFileExit_Click(object sender, System.EventArgs e)
        {
            this.Close();
        }

        /// <summary>
        /// Show About Box
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void mnuHelpAbout_Click(object sender, System.EventArgs e)
        {
            MessageBox.Show(
                this,
                "Programa feito para Mover pastas\n" + 
                "Software sob a Gnu Public License");
        
        }

        /// <summary>
        /// File - Open menu item
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void mnuFileOpen_Click(object sender, System.EventArgs e)
        {
            
            // Show Open File dialog

            /*
            OpenFileDialog openDlg = new OpenFileDialog();
            openDlg.Filter  = "All Files (*.*)|*.*";

            openDlg.InitialDirectory = Directory.GetCurrentDirectory();
            openDlg.FileName = "" ;
            openDlg.CheckFileExists = true;
            openDlg.CheckPathExists = true;
            openDlg.Multiselect = true;

            if ( openDlg.ShowDialog() != DialogResult.OK )
                return;

            // Call OpenFiles function passing array of strings to it
            OpenFiles(openDlg.FileNames);
             * */
        }


        #endregion

        private void lstFiles_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void menuItem1_Click(object sender, EventArgs e)
        {

        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
         
            
                
            
        }

      

        private void camCurso_HelpRequest(object sender, EventArgs e)
        {

        }

        private void checkBox1_CheckedChanged_1(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }



	}
}
